/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors } from '../models/errors';

/**
 * Creates an instance of AuthOauth2Token400Error1
 */
interface AuthOauth2Token400Error1 {
  errors?: Errors;
}

export class AuthOauth2Token400Error1Error extends ApiError<AuthOauth2Token400Error1> {}
