/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors } from '../models/errors';

/**
 * Creates an instance of InsuredRisks401Error1
 */
interface InsuredRisks401Error1 {
  errors?: Errors;
}

export class InsuredRisks401Error1Error extends ApiError<InsuredRisks401Error1> {}
