/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors1 } from '../models/errors1';

/**
 * Creates an instance of InsuredRisks403Error1
 */
interface InsuredRisks403Error1 {
  errors?: Errors1[];
}

export class InsuredRisks403Error1Error extends ApiError<InsuredRisks403Error1> {}
