/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors1 } from '../models/errors1';

/**
 * Creates an instance of InsuredRisks400Error1
 */
interface InsuredRisks400Error1 {
  errors?: Errors1[];
}

export class InsuredRisks400Error1Error extends ApiError<InsuredRisks400Error1> {}
