/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors1 } from '../models/errors1';

/**
 * Creates an instance of InsuredRisks415Error1
 */
interface InsuredRisks415Error1 {
  errors?: Errors1[];
}

export class InsuredRisks415Error1Error extends ApiError<InsuredRisks415Error1> {}
