/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors1 } from '../models/errors1';

/**
 * Creates an instance of Policies500Error1
 */
interface Policies500Error1 {
  errors?: Errors1[];
}

export class Policies500Error1Error extends ApiError<Policies500Error1> {}
