/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors1 } from '../models/errors1';

/**
 * Creates an instance of Policies400Error1
 */
interface Policies400Error1 {
  errors?: Errors1[];
}

export class Policies400Error1Error extends ApiError<Policies400Error1> {}
