/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors1 } from '../models/errors1';

/**
 * Creates an instance of Policies403Error1
 */
interface Policies403Error1 {
  errors?: Errors1[];
}

export class Policies403Error1Error extends ApiError<Policies403Error1> {}
