/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors } from '../models/errors';

/**
 * Creates an instance of Policies401Error1
 */
interface Policies401Error1 {
  errors?: Errors;
}

export class Policies401Error1Error extends ApiError<Policies401Error1> {}
