/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors } from '../models/errors';

/**
 * Creates an instance of Quotes401Error1
 */
interface Quotes401Error1 {
  errors?: Errors;
}

export class Quotes401Error1Error extends ApiError<Quotes401Error1> {}
