/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors1 } from '../models/errors1';

/**
 * Creates an instance of Quotes500Error1
 */
interface Quotes500Error1 {
  errors?: Errors1[];
}

export class Quotes500Error1Error extends ApiError<Quotes500Error1> {}
