/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AcceptEnum
 */
export enum AcceptEnum {
  EnumApplicationvndapijson = 'application/vnd.api+json',
}

/**
 * Schema for AcceptEnum
 */
export const acceptEnumSchema: Schema<AcceptEnum> = stringEnum(AcceptEnum);
