/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data1, data1Schema } from './data1';

/** UUID of the agent. */
export interface Agent {
  /** Provided data for this agent relationship. */
  data: Data1;
}

export const agentSchema: Schema<Agent> = object({
  data: ['data', lazy(() => data1Schema)],
});
