/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data1, data1Schema } from './data1';

/** UUID that identifies this agent. */
export interface Agent3 {
  /** Provided data for this agent relationship. */
  data: Data1;
}

export const agent3Schema: Schema<Agent3> = object({
  data: ['data', lazy(() => data1Schema)],
});
