/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data43, data43Schema } from './data43';

/** The Boost UUID of the agent. */
export interface Agent6 {
  /** Provided data for this product relationship. */
  data: Data43;
}

export const agent6Schema: Schema<Agent6> = object({
  data: ['data', lazy(() => data43Schema)],
});
