/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, unknown } from '../schema';

/** The insured risk. */
export interface Attributes12 {
  /** Object representation of the insured risk. */
  factors?: unknown;
}

export const attributes12Schema: Schema<Attributes12> = object({
  factors: ['factors', optional(unknown())],
});
