/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Attributes of this coverage. */
export interface Attributes4 {
  /** Date time when this resource was created in our system. */
  createdDate: string;
  /** Date time when this resource was last modified in our system. */
  modifiedDate: string;
  /**
   * A value from the set denoting the user-selected deductible of coverage. This is dependent
   * on the product's configuration.
   */
  deductible: string;
  /**
   * A value from the set denoting the user-selected limit of coverage. This is dependent
   * on the product's configuration.
   */
  limit: string;
  /** Term premium for this coverage */
  premium: string;
  /** Additional fees relating to this coverage. */
  additionalFees: string;
  /** Date for when this coverage goes into effect on the policy. */
  revisionDate: string;
}

export const attributes4Schema: Schema<Attributes4> = object({
  createdDate: ['created_date', string()],
  modifiedDate: ['modified_date', string()],
  deductible: ['deductible', string()],
  limit: ['limit', string()],
  premium: ['premium', string()],
  additionalFees: ['additional_fees', string()],
  revisionDate: ['revision_date', string()],
});
