/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';

/** Attributes for this object. */
export interface Attributes10 {
  /**
   * A value from the set denoting the user-selected deductible of coverage. This is dependent
   * on the product's configuration.
   */
  deductible?: string;
  /**
   * A value from the set denoting the user-selected limit of coverage. This is dependent
   * on the product's configuration.
   */
  limit?: string;
  /** Calculated premium for this coverage which is included in the policy's term premium. */
  premium?: string;
  /** Additional data about the policy. The required metadata fields are specific to the product. */
  metadata?: unknown;
}

export const attributes10Schema: Schema<Attributes10> = object({
  deductible: ['deductible', optional(string())],
  limit: ['limit', optional(string())],
  premium: ['premium', optional(string())],
  metadata: ['metadata', optional(unknown())],
});
