/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Attributes for this policy. */
export interface Attributes2 {
  /** Quote number received from quote creation. */
  quoteNumber: string;
  /**
   * Value from the set which controls invoicing and billing. This is dependent
   * on your product's configuration.
   */
  installmentPlan: string;
  /** Stripe credit card token that will be used for charge authorization. */
  stripeToken: string;
  /** Any value you wish to associate with this resource such as an ID from your system. */
  externalId?: string;
}

export const attributes2Schema: Schema<Attributes2> = object({
  quoteNumber: ['quote_number', string()],
  installmentPlan: ['installment_plan', string()],
  stripeToken: ['stripe_token', string()],
  externalId: ['external_id', optional(string())],
});
