/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';

/** Attributes of this insured risk. */
export interface Attributes5 {
  /** Date time when this resource was created in our system. */
  createdDate: string;
  /** Date time when this resource was last modified in our system. */
  modifiedDate: string;
  /** Specific ratable factors that apply to this Insured Risk. The content must fully adhere to a product-specific, pre-defined schema. */
  factors?: unknown;
}

export const attributes5Schema: Schema<Attributes5> = object({
  createdDate: ['created_date', string()],
  modifiedDate: ['modified_date', string()],
  factors: ['factors', optional(unknown())],
});
