/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { ExpiresInEnum, expiresInEnumSchema } from './expiresInEnum';
import { TokenTypeEnum, tokenTypeEnumSchema } from './tokenTypeEnum';

export interface AuthOauth2TokenResponse {
  /** Type of token. */
  tokenType?: TokenTypeEnum;
  /** The token to be used in future API calls. */
  accessToken?: string;
  /** How long this token is valid for. */
  expiresIn?: ExpiresInEnum;
}

export const authOauth2TokenResponseSchema: Schema<AuthOauth2TokenResponse> = object(
  {
    tokenType: ['token_type', optional(tokenTypeEnumSchema)],
    accessToken: ['access_token', optional(string())],
    expiresIn: ['expires_in', optional(expiresInEnumSchema)],
  }
);
