/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ContentType1Enum
 */
export enum ContentType1Enum {
  EnumApplicationvndapijson = 'application/vnd.api+json',
}

/**
 * Schema for ContentType1Enum
 */
export const contentType1EnumSchema: Schema<ContentType1Enum> = stringEnum(ContentType1Enum);
