/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Data7, data7Schema } from './data7';
import { Meta, metaSchema } from './meta';

/** List of coverages that apply to this policy. */
export interface Coverages {
  /** List of coverages. */
  data: Data7[];
  /** Additional meta information about this data. */
  meta?: Meta;
}

export const coveragesSchema: Schema<Coverages> = object({
  data: ['data', array(lazy(() => data7Schema))],
  meta: ['meta', optional(lazy(() => metaSchema))],
});
