/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Data40, data40Schema } from './data40';

/** List of coverages that will be created at the same time as this resource. */
export interface Coverages2 {
  /** List of objects with coverage local IDs. */
  data: Data40[];
}

export const coverages2Schema: Schema<Coverages2> = object({
  data: ['data', array(lazy(() => data40Schema))],
});
