/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data21, data21Schema } from './data21';

/** UUID that identifies this product coverage. */
export interface Coverage {
  /** Provided data for this product coverage relationship. */
  data: Data21;
}

export const coverageSchema: Schema<Coverage> = object({
  data: ['data', lazy(() => data21Schema)],
});
