/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data12, data12Schema } from './data12';

/** Relationship containing the id that identifies the customer for this policy. */
export interface Customer {
  /** Provided data for this customer relationship. */
  data: Data12;
}

export const customerSchema: Schema<Customer> = object({
  data: ['data', lazy(() => data12Schema)],
});
