/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data41, data41Schema } from './data41';

/** Customer that will be created at the same time as this resource. */
export interface Customer2 {
  /** Provided data for this customer relationship with local ID. */
  data: Data41;
}

export const customer2Schema: Schema<Customer2> = object({
  data: ['data', lazy(() => data41Schema)],
});
