/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Attributes3, attributes3Schema } from './attributes3';
import { Relationships3, relationships3Schema } from './relationships3';

export interface Data9 {
  /** The type of resource being represented. */
  type: string;
  id: string;
  /** Attributes that describe a policy resource with optional writeable money fields. */
  attributes: Attributes3;
  /** Items related to this policy. */
  relationships: Relationships3;
}

export const data9Schema: Schema<Data9> = object({
  type: ['type', string()],
  id: ['id', string()],
  attributes: ['attributes', lazy(() => attributes3Schema)],
  relationships: ['relationships', lazy(() => relationships3Schema)],
});
