/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Attributes1, attributes1Schema } from './attributes1';
import { Relationships1, relationships1Schema } from './relationships1';

export interface Data3 {
  /** The type of resource being represented. */
  type: string;
  id: string;
  /** Attributes that describe an Insured Risk. */
  attributes: Attributes1;
  /** Related objects. */
  relationships: Relationships1;
}

export const data3Schema: Schema<Data3> = object({
  type: ['type', string()],
  id: ['id', string()],
  attributes: ['attributes', lazy(() => attributes1Schema)],
  relationships: ['relationships', lazy(() => relationships1Schema)],
});
