/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Provided data for this product relationship. */
export interface Data43 {
  /** The type of resource being represented. */
  type: string;
  /** Unique Boost-generated UUID that identifies this resource. */
  id: string;
}

export const data43Schema: Schema<Data43> = object({
  type: ['type', string()],
  id: ['id', string()],
});
