/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Attributes9, attributes9Schema } from './attributes9';
import { Relationships9, relationships9Schema } from './relationships9';

/** All values for the request are in this top-level object. */
export interface Data39 {
  /** The type of resource being represented. */
  type: string;
  /** Attributes for this object. */
  attributes: Attributes9;
  /** Related items. */
  relationships: Relationships9;
}

export const data39Schema: Schema<Data39> = object({
  type: ['type', string()],
  attributes: ['attributes', lazy(() => attributes9Schema)],
  relationships: ['relationships', lazy(() => relationships9Schema)],
});
