/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Attributes, attributesSchema } from './attributes';
import { Relationships, relationshipsSchema } from './relationships';

/** All values that describe this Insured Risk resource. */
export interface Data {
  /** The type of resource being represented. */
  type: string;
  id?: string;
  /** Attributes that describe an Insured Risk. */
  attributes: Attributes;
  /** Related objects. */
  relationships: Relationships;
}

export const dataSchema: Schema<Data> = object({
  type: ['type', string()],
  id: ['id', optional(string())],
  attributes: ['attributes', lazy(() => attributesSchema)],
  relationships: ['relationships', lazy(() => relationshipsSchema)],
});
