/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Attributes9, attributes9Schema } from './attributes9';
import { Relationships11, relationships11Schema } from './relationships11';

/** All values for this quote are in this top-level object. */
export interface Data45 {
  /** The type of resource being represented. */
  type: string;
  /** Unique Boost generated identifier for this resource that adheres to the above pattern. */
  id: string;
  /** Attributes for this object. */
  attributes: Attributes9;
  /** Related items. */
  relationships: Relationships11;
}

export const data45Schema: Schema<Data45> = object({
  type: ['type', string()],
  id: ['id', string()],
  attributes: ['attributes', lazy(() => attributes9Schema)],
  relationships: ['relationships', lazy(() => relationships11Schema)],
});
