/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Attributes2, attributes2Schema } from './attributes2';
import { Relationships2, relationships2Schema } from './relationships2';

/** Data for creating a policy from a quote requiring a stripe token. */
export interface Data6 {
  /** The type of resource being represented. */
  type: string;
  /** Attributes for this policy. */
  attributes: Attributes2;
  /** Related items. */
  relationships: Relationships2;
}

export const data6Schema: Schema<Data6> = object({
  type: ['type', string()],
  attributes: ['attributes', lazy(() => attributes2Schema)],
  relationships: ['relationships', lazy(() => relationships2Schema)],
});
