/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Provided data for this endorsement relationship. */
export interface Data20 {
  /** Name of this related object. Must be `endorsement`. */
  type: string;
  /** UUID that identifies this resource. */
  id: string;
}

export const data20Schema: Schema<Data20> = object({
  type: ['type', string()],
  id: ['id', string()],
});
