/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data20, data20Schema } from './data20';

/** UUID that identifies this endorsement. */
export interface Endorsement {
  /** Provided data for this endorsement relationship. */
  data: Data20;
}

export const endorsementSchema: Schema<Endorsement> = object({
  data: ['data', lazy(() => data20Schema)],
});
