/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EntityTypeEnum
 */
export enum EntityTypeEnum {
  Person = 'person',
  Business = 'business',
}

/**
 * Schema for EntityTypeEnum
 */
export const entityTypeEnumSchema: Schema<EntityTypeEnum> = stringEnum(EntityTypeEnum);
