/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Errors1 {
  /** Type of error. */
  title?: string;
  /** Detailed information about the error. */
  detail?: string;
}

export const errors1Schema: Schema<Errors1> = object({
  title: ['title', optional(string())],
  detail: ['detail', optional(string())],
});
