/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema';

/**
 * Enum for ExpiresInEnum
 */
export enum ExpiresInEnum {
  Enum7200 = 7200,
}

/**
 * Schema for ExpiresInEnum
 */
export const expiresInEnumSchema: Schema<ExpiresInEnum> = numberEnum(ExpiresInEnum);
