/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Attributes12, attributes12Schema } from './attributes12';
import { Relationships14, relationships14Schema } from './relationships14';

export interface Included42 {
  /** The type of resource being represented. */
  type: string;
  /** Unique Boost-generated UUID that identifies this resource. */
  id: string;
  /** The local ID that ties this resource to a related object in `data.relationships`. */
  lid: string;
  /** The insured risk. */
  attributes: Attributes12;
  /** Related items. */
  relationships: Relationships14;
}

export const included42Schema: Schema<Included42> = object({
  type: ['type', string()],
  id: ['id', string()],
  lid: ['lid', string()],
  attributes: ['attributes', lazy(() => attributes12Schema)],
  relationships: ['relationships', lazy(() => relationships14Schema)],
});
