/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Attributes12, attributes12Schema } from './attributes12';

export interface Included32 {
  /** The type of resource being represented. */
  type: string;
  /** The local ID that ties this resource to a related object in `data.relationships`. */
  lid: string;
  /** The insured risk. */
  attributes: Attributes12;
}

export const included32Schema: Schema<Included32> = object({
  type: ['type', string()],
  lid: ['lid', string()],
  attributes: ['attributes', lazy(() => attributes12Schema)],
});
