/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Attributes4, attributes4Schema } from './attributes4';
import { Relationships4, relationships4Schema } from './relationships4';

export interface Included {
  /** The type of resource being represented. */
  type: string;
  /** UUID that identifies this resource. */
  id: string;
  /** Attributes of this coverage. */
  attributes: Attributes4;
  /** Items related to this coverage. */
  relationships: Relationships4;
}

export const includedSchema: Schema<Included> = object({
  type: ['type', string()],
  id: ['id', string()],
  attributes: ['attributes', lazy(() => attributes4Schema)],
  relationships: ['relationships', lazy(() => relationships4Schema)],
});
