/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Attributes10, attributes10Schema } from './attributes10';
import { Relationships10, relationships10Schema } from './relationships10';

export interface Included4 {
  /** The type of resource being represented. */
  type: string;
  /** Unique Boost-generated UUID that identifies this resource. */
  id: string;
  /** The local ID that ties this resource to a related object in `data.relationships`. */
  lid: string;
  /** Attributes for this object. */
  attributes: Attributes10;
  /** Related items. */
  relationships: Relationships10;
}

export const included4Schema: Schema<Included4> = object({
  type: ['type', string()],
  id: ['id', string()],
  lid: ['lid', string()],
  attributes: ['attributes', lazy(() => attributes10Schema)],
  relationships: ['relationships', lazy(() => relationships10Schema)],
});
