/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Attributes11, attributes11Schema } from './attributes11';
import { Relationships13, relationships13Schema } from './relationships13';

export interface Included41 {
  /** The type of resource being represented. */
  type: string;
  /** Unique Boost-generated UUID that identifies this resource. */
  id: string;
  /** The local ID that ties this resource to a related object in `data.relationships`. */
  lid: string;
  /** The insured entity. */
  attributes: Attributes11;
  /** Related items. */
  relationships: Relationships13;
}

export const included41Schema: Schema<Included41> = object({
  type: ['type', string()],
  id: ['id', string()],
  lid: ['lid', string()],
  attributes: ['attributes', lazy(() => attributes11Schema)],
  relationships: ['relationships', lazy(() => relationships13Schema)],
});
