/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Attributes5, attributes5Schema } from './attributes5';
import { Relationships5, relationships5Schema } from './relationships5';

export interface Included1 {
  /** The type of resource being represented. */
  type: string;
  /** UUID that identifies this resource. */
  id: string;
  /** Attributes of this insured risk. */
  attributes: Attributes5;
  /** Items related to this insured risk. */
  relationships: Relationships5;
}

export const included1Schema: Schema<Included1> = object({
  type: ['type', string()],
  id: ['id', string()],
  attributes: ['attributes', lazy(() => attributes5Schema)],
  relationships: ['relationships', lazy(() => relationships5Schema)],
});
