/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data18, data18Schema } from './data18';

/** The Boost UUID for the `installment_plan` based on the chosen installment plan. */
export interface InstallmentPlan {
  /** Provided data for this installment plan relationship. */
  data: Data18;
}

export const installmentPlanSchema: Schema<InstallmentPlan> = object({
  data: ['data', lazy(() => data18Schema)],
});
