/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface InstallmentPlan2 {
  /** The billing period for this installment plan entry. */
  billingPeriod: string;
  /** Boost generated amount due for this installment plan entry. */
  amountDue: string;
  /** The date on which payment is due for this billing period. */
  dueDate: string;
  /** Boost generated taxes due for this installment plan entry. */
  taxes: string;
  /** Boost generated fees due for this installment plan entry. */
  fees: string;
}

export const installmentPlan2Schema: Schema<InstallmentPlan2> = object({
  billingPeriod: ['billing_period', string()],
  amountDue: ['amount_due', string()],
  dueDate: ['due_date', string()],
  taxes: ['taxes', string()],
  fees: ['fees', string()],
});
