/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data42, data42Schema } from './data42';

/** Insured risk that will be created at the same time as this resource. */
export interface InsuredRisk2 {
  /** Provided data for this insured risk relationship with local ID. */
  data: Data42;
}

export const insuredRisk2Schema: Schema<InsuredRisk2> = object({
  data: ['data', lazy(() => data42Schema)],
});
