/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data11, data11Schema } from './data11';

/** The risk insured by the policy. */
export interface InsuredRisk {
  /** Provided data for this insured risk relationship. */
  data: Data11;
}

export const insuredRiskSchema: Schema<InsuredRisk> = object({
  data: ['data', lazy(() => data11Schema)],
});
