/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data, dataSchema } from './data';

export interface InsuredRisksRequest {
  /** All values that describe this Insured Risk resource. */
  data: Data;
}

export const insuredRisksRequestSchema: Schema<InsuredRisksRequest> = object({
  data: ['data', lazy(() => dataSchema)],
});
