/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data8, data8Schema } from './data8';

/** ID of parent policy. Product must also be a parent product. */
export interface Parent {
  /** Provided data for this parent policy relationship. */
  data: Data8;
}

export const parentSchema: Schema<Parent> = object({
  data: ['data', lazy(() => data8Schema)],
});
