/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data6, data6Schema } from './data6';

export interface PoliciesRequest {
  /** Data for creating a policy from a quote requiring a stripe token. */
  data: Data6;
}

export const policiesRequestSchema: Schema<PoliciesRequest> = object({
  data: ['data', lazy(() => data6Schema)],
});
