/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Data24, data24Schema } from './data24';

export interface PoliciesResponse1 {
  /** Array of policy objects. */
  data: Data24[];
}

export const policiesResponse1Schema: Schema<PoliciesResponse1> = object({
  data: ['data', array(lazy(() => data24Schema))],
});
