/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data19, data19Schema } from './data19';

/** UUID that identifies this policy. */
export interface Policy {
  /** Provided data for this policy relationship. */
  data: Data19;
}

export const policySchema: Schema<Policy> = object({
  data: ['data', lazy(() => data19Schema)],
});
