/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data2, data2Schema } from './data2';

/**
 * Boost supplied value representing the specific product type. The product's configuration
 * Determines allowable values, such as limit and deductible.
 */
export interface Product2 {
  /** Provided data for this product relationship. */
  data: Data2;
}

export const product2Schema: Schema<Product2> = object({
  data: ['data', lazy(() => data2Schema)],
});
