/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data2, data2Schema } from './data2';

/** UUID that identifies this product. */
export interface Product3 {
  /** Provided data for this product relationship. */
  data: Data2;
}

export const product3Schema: Schema<Product3> = object({
  data: ['data', lazy(() => data2Schema)],
});
