/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Data44, data44Schema } from './data44';

/** Product coverage that applies to this policy. */
export interface ProductCoverage {
  /** Provided data for this product coverage relationship. */
  data: Data44;
}

export const productCoverageSchema: Schema<ProductCoverage> = object({
  data: ['data', lazy(() => data44Schema)],
});
