/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, unknown } from '../schema';
import { Data45, data45Schema } from './data45';

/** Data representing a quote. */
export interface QuotesResponse {
  /** All values for this quote are in this top-level object. */
  data: Data45;
  /** Array of included objects. */
  included: unknown[];
}

export const quotesResponseSchema: Schema<QuotesResponse> = object({
  data: ['data', lazy(() => data45Schema)],
  included: ['included', array(unknown())],
});
