/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  AdditionalInterests,
  additionalInterestsSchema,
} from './additionalInterests';
import { Parent, parentSchema } from './parent';

/** Related items. */
export interface Relationships2 {
  /** List of additional interests for this policy. */
  additionalInterests?: AdditionalInterests;
  /** ID of parent policy. Product must also be a parent product. */
  parent?: Parent;
}

export const relationships2Schema: Schema<Relationships2> = object({
  additionalInterests: [
    'additional_interests',
    optional(lazy(() => additionalInterestsSchema)),
  ],
  parent: ['parent', optional(lazy(() => parentSchema))],
});
