/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Agent3, agent3Schema } from './agent3';
import { Product3, product3Schema } from './product3';

/** Items related to this insured risk. */
export interface Relationships5 {
  /** UUID that identifies this product. */
  product: Product3;
  /** UUID that identifies this agent. */
  agent: Agent3;
}

export const relationships5Schema: Schema<Relationships5> = object({
  product: ['product', lazy(() => product3Schema)],
  agent: ['agent', lazy(() => agent3Schema)],
});
