/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Coverage, coverageSchema } from './coverage';
import { Endorsement, endorsementSchema } from './endorsement';
import { Policy, policySchema } from './policy';

/** Items related to this coverage. */
export interface Relationships4 {
  /** UUID that identifies this policy. */
  policy: Policy;
  /** UUID that identifies this endorsement. */
  endorsement: Endorsement;
  /** UUID that identifies this product coverage. */
  coverage: Coverage;
}

export const relationships4Schema: Schema<Relationships4> = object({
  policy: ['policy', lazy(() => policySchema)],
  endorsement: ['endorsement', lazy(() => endorsementSchema)],
  coverage: ['coverage', lazy(() => coverageSchema)],
});
