/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Agent, agentSchema } from './agent';
import { Product, productSchema } from './product';

/** Related objects. */
export interface Relationships1 {
  /** UUID of the agent. */
  agent: Agent;
  /**
   * Boost supplied value representing the specific product type. The product's configuration
   * Determines allowable values, such as limits and deductibles.
   */
  product: Product;
}

export const relationships1Schema: Schema<Relationships1> = object({
  agent: ['agent', lazy(() => agentSchema)],
  product: ['product', lazy(() => productSchema)],
});
