/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Agent6, agent6Schema } from './agent6';

/** Related items. */
export interface Relationships13 {
  /** The Boost UUID of the agent. */
  agent: Agent6;
}

export const relationships13Schema: Schema<Relationships13> = object({
  agent: ['agent', lazy(() => agent6Schema)],
});
