/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Coverages2, coverages2Schema } from './coverages2';
import { Customer2, customer2Schema } from './customer2';
import { InsuredRisk2, insuredRisk2Schema } from './insuredRisk2';
import { Product6, product6Schema } from './product6';

/** Related items. */
export interface Relationships9 {
  /** List of coverages that will be created at the same time as this resource. */
  coverages?: Coverages2;
  /** Customer that will be created at the same time as this resource. */
  customer: Customer2;
  /** Insured risk that will be created at the same time as this resource. */
  insuredRisk?: InsuredRisk2;
  /**
   * Boost supplied value representing the specific product type. The product's configuration
   * will determine allowable values for the Policy, such as limit and deductible.
   */
  product: Product6;
}

export const relationships9Schema: Schema<Relationships9> = object({
  coverages: ['coverages', optional(lazy(() => coverages2Schema))],
  customer: ['customer', lazy(() => customer2Schema)],
  insuredRisk: ['insured_risk', optional(lazy(() => insuredRisk2Schema))],
  product: ['product', lazy(() => product6Schema)],
});
