/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Agent6, agent6Schema } from './agent6';
import { Coverages3, coverages3Schema } from './coverages3';
import { Customer3, customer3Schema } from './customer3';
import { InsuredRisk3, insuredRisk3Schema } from './insuredRisk3';
import { Product6, product6Schema } from './product6';

/** Related items. */
export interface Relationships11 {
  /** List of coverages that were created. */
  coverages?: Coverages3;
  /** Customer that was created. */
  customer: Customer3;
  /** Insured risk attached to the quote. */
  insuredRisk: InsuredRisk3;
  /**
   * Boost supplied value representing the specific product type. The product's configuration
   * will determine allowable values for the Policy, such as limit and deductible.
   */
  product: Product6;
  /** The Boost UUID of the agent. */
  agent?: Agent6;
}

export const relationships11Schema: Schema<Relationships11> = object({
  coverages: ['coverages', optional(lazy(() => coverages3Schema))],
  customer: ['customer', lazy(() => customer3Schema)],
  insuredRisk: ['insured_risk', lazy(() => insuredRisk3Schema)],
  product: ['product', lazy(() => product6Schema)],
  agent: ['agent', optional(lazy(() => agent6Schema))],
});
