/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Agent, agentSchema } from './agent';
import { Product, productSchema } from './product';

/** Related objects. */
export interface Relationships {
  /** UUID of the agent. */
  agent?: Agent;
  /**
   * Boost supplied value representing the specific product type. The product's configuration
   * Determines allowable values, such as limits and deductibles.
   */
  product: Product;
}

export const relationshipsSchema: Schema<Relationships> = object({
  agent: ['agent', optional(lazy(() => agentSchema))],
  product: ['product', lazy(() => productSchema)],
});
