/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StatusEnum
 */
export enum StatusEnum {
  Issued = 'issued',
  Inforce = 'in-force',
  Reinstated = 'reinstated',
  Renewed = 'renewed',
  Cancelpending = 'cancel-pending',
  Cancelled = 'cancelled',
  Void = 'void',
}

/**
 * Schema for StatusEnum
 */
export const statusEnumSchema: Schema<StatusEnum> = stringEnum(StatusEnum);
